[workspace]
resolver = "3"
members = [
    "protocols",
    "parsers/v1",
    "renderer",
    "tokenizers",
    "conformance",
    "parsers/v2",
    "parsers/v2-py",
    "examples/dynamo-demo-server",
]

[workspace.package]
edition = "2024"
authors = ["NVIDIA Inc. <sw-dl-dynamo@nvidia.com>"]
homepage = "https://github.com/ai-dynamo/frontend-crates"
repository = "https://github.com/ai-dynamo/frontend-crates.git"

[workspace.dependencies]
aho-corasick = "1"
anyhow = "1"
async-openai = { version = "0.41", default-features = false }
async-stream = "0.3"
axum = "0.8"
base64 = "0.22"
basetenkenizer = { version = "0.2.8", default-features = false }
blake3 = "1"
chrono = { version = "0.4", default-features = false, features = [
    "alloc",
    "std",
    "clock",
    "now",
    "serde",
] }
clap = "4"
derive_builder = "0.20"
dynamo-parsers = { path = "parsers/v1", version = "8.2.0" }
dynamo-protocols = { path = "protocols", version = "5.4.1" }
dynamo-renderer = { path = "renderer", version = "5.1.2" }
dynamo-tokenizers = { path = "tokenizers", version = "1.8.1" }
either = { version = "1.13", features = ["serde"] }
fastokens = "0.3.1"
futures = "0.3"
hf-hub = { version = "1.0", default-features = false, features = ["rustls-tls"] }
jsonschema = { version = "0.53", default-features = false }
minijinja = { version = "2.24.0" }
minijinja-contrib = { version = "2.24.0" }
moka = { version = "0.12" }
num-traits = "0.2"
openai-harmony = "0.0.8"
pyo3 = { version = "0.22", features = ["extension-module"] }
rayon = "1"
regex = "1"
rstest = "0.25"
rustc-hash = "1.1"
ruff-python-ast = { package = "rustpython-ruff_python_ast", version = "0.15.8" }
ruff-python-parser = { package = "rustpython-ruff_python_parser", version = "0.15.8" }
serde = "1"
serde_json = "1"
strum = "0.27"
tempfile = "3"
thiserror = "2.0.17"
tiktoken-rs = { version = "0.9", default-features = false }
tokio = "1.48"
tokio-test = "0.4.4"
tokenizers = { version = "0.21.4", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.5"
uuid = "1.18.1"
